version: "3.3"
services:
   rethinkdb:
      image: rethinkdb:2.3.6
   migrator:
      image: sequeless/migrator:latest
      build:
         context: ./services/migrator
      restart: "no"
      depends_on:
         - rethinkdb
