version: "3.3"
services:
   rethinkdb:
      image: rethinkdb:2.3.6
      ports:
         - "8080:8080"
         - "28015:28015"
   migrator:
      image: ${REGISTRY_HOST}/${REGISTRY_NAMESPACE}/migrator
      build:
         context: ./services/migrator
      restart: "no"
      depends_on:
         - rethinkdb
